### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by marecl** [marecl/MULoader#3]
- [ ] iHex support  
- [ ] tag address range (where to write)
- [ ] debug branch
- [ ] Move to avrstudio entirely
- [ ] integrate uploader with IDE
